# Generated by Django 5.1.2 on 2024-12-30 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateCanEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('process', models.CharField(default='', max_length=50)),
                ('volume', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
                ('qty', models.IntegerField(default=0)),
                ('content', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetailVolumeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_this_items_qty_per_product', models.IntegerField(default=0)),
                ('all_this_items_qty', models.IntegerField(default=0)),
                ('this_item_volume', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVolumeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_volume', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
                ('all_product_volume', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
                ('all_product_qty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QtyProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBN', models.IntegerField(default=0)),
                ('DONG_GOI', models.IntegerField(default=0)),
                ('TON_KHO', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('letter', models.CharField(default='', max_length=5, null=True)),
                ('dest', models.CharField(default='', max_length=50, null=True)),
                ('date', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfactory.datecanedit')),
            ],
        ),
        migrations.AddField(
            model_name='datecanedit',
            name='bookingCutoff',
            field=models.ManyToManyField(related_name='bookingCutoff_shipcaneditinfor', to='appfactory.dateitem'),
        ),
        migrations.AddField(
            model_name='datecanedit',
            name='bookingEtd',
            field=models.ManyToManyField(related_name='bookingEtd_shipcaneditinfor', to='appfactory.dateitem'),
        ),
        migrations.AddField(
            model_name='datecanedit',
            name='cyCut',
            field=models.ManyToManyField(related_name='cycut_shipcaneditinfor', to='appfactory.dateitem'),
        ),
        migrations.AddField(
            model_name='datecanedit',
            name='etdVietNam',
            field=models.ManyToManyField(related_name='etdVietNam_shipcaneditinfor', to='appfactory.dateitem'),
        ),
        migrations.AddField(
            model_name='datecanedit',
            name='loadContTT',
            field=models.ManyToManyField(related_name='loadContTT_shipcaneditinfor', to='appfactory.dateitem'),
        ),
        migrations.AddField(
            model_name='datecanedit',
            name='monthShip',
            field=models.ManyToManyField(related_name='monthShip_shipcaneditinfor', to='appfactory.dateitem'),
        ),
        migrations.AddField(
            model_name='datecanedit',
            name='psi',
            field=models.ManyToManyField(related_name='psi_shipcaneditinfor', to='appfactory.dateitem'),
        ),
        migrations.AddField(
            model_name='datecanedit',
            name='shipRun',
            field=models.ManyToManyField(related_name='shiprun_shipcaneditinfor', to='appfactory.dateitem'),
        ),
        migrations.AddField(
            model_name='datecanedit',
            name='siCut',
            field=models.ManyToManyField(related_name='sicut_shipcaneditinfor', to='appfactory.dateitem'),
        ),
        migrations.CreateModel(
            name='DetailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(default='', max_length=40, null=True)),
                ('code', models.CharField(default='', max_length=255, null=True)),
                ('po', models.CharField(default='', max_length=255, null=True)),
                ('product_name', models.CharField(default='', max_length=255, null=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('length', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('depth', models.FloatField(default=0.0)),
                ('date', models.ManyToManyField(to='appfactory.dateitem')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfactory.detailvolumeitem')),
                ('product_volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfactory.productvolumeitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_count', models.IntegerField(default=0)),
                ('code', models.CharField(default='', max_length=255, null=True)),
                ('details', models.ManyToManyField(to='appfactory.detailitem')),
            ],
        ),
        migrations.CreateModel(
            name='ShipDetailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50, null=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('color', models.CharField(default='', max_length=50, null=True)),
                ('qty', models.CharField(default='', max_length=50, null=True)),
                ('client', models.CharField(default='', max_length=50, null=True)),
                ('contifor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfactory.continfor')),
                ('qtyByProcess', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfactory.qtyprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ShipInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerName', models.CharField(default='', max_length=50, null=True)),
                ('code', models.CharField(default='', max_length=50, null=True)),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('sheetname', models.CharField(default='', max_length=50, null=True)),
                ('poContent', models.CharField(default='', max_length=50, null=True)),
                ('poName', models.CharField(default='', max_length=50, null=True)),
                ('clientName', models.CharField(default='', max_length=50, null=True)),
                ('status', models.CharField(default='', max_length=50, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('poEtd', models.ManyToManyField(related_name='poetd_shipcaneditinfor', to='appfactory.dateitem')),
                ('qtyProcess', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfactory.qtyprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ShipQtyByContainerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('contifor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfactory.continfor')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfactory.shipdetailitem')),
            ],
        ),
    ]
