# Generated by Django 5.1.2 on 2025-01-03 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('process', models.CharField(default='', max_length=50)),
                ('volume', models.FloatField(default=0.0)),
                ('qty', models.IntegerField(default=0)),
                ('content', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetailVolumeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_this_items_qty_per_product', models.IntegerField(default=0)),
                ('all_this_items_qty', models.IntegerField(default=0)),
                ('this_item_volume', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVolumeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_volume', models.FloatField(default=0.0)),
                ('all_product_volume', models.FloatField(default=0.0)),
                ('all_product_qty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QtyProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBN', models.IntegerField(default=0)),
                ('DONG_GOI', models.IntegerField(default=0)),
                ('TON_KHO', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DateCanEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingCutoff', models.ManyToManyField(related_name='bookingCutoff_shipcaneditinfor', to='appfactory.dateitem')),
                ('bookingEtd', models.ManyToManyField(related_name='bookingEtd_shipcaneditinfor', to='appfactory.dateitem')),
                ('cyCut', models.ManyToManyField(related_name='cycut_shipcaneditinfor', to='appfactory.dateitem')),
                ('etd', models.ManyToManyField(related_name='etdVietNam_shipcaneditinfor', to='appfactory.dateitem')),
                ('loadContTT', models.ManyToManyField(related_name='loadContTT_shipcaneditinfor', to='appfactory.dateitem')),
                ('monthShip', models.ManyToManyField(related_name='monthShip_shipcaneditinfor', to='appfactory.dateitem')),
                ('psi', models.ManyToManyField(related_name='psi_shipcaneditinfor', to='appfactory.dateitem')),
                ('shipRun', models.ManyToManyField(related_name='shiprun_shipcaneditinfor', to='appfactory.dateitem')),
                ('siCut', models.ManyToManyField(related_name='sicut_shipcaneditinfor', to='appfactory.dateitem')),
            ],
        ),
        migrations.CreateModel(
            name='DetailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(default='', max_length=40, null=True)),
                ('code', models.CharField(default='', max_length=255, null=True)),
                ('po', models.CharField(default='', max_length=255, null=True)),
                ('product_name', models.CharField(default='', max_length=255, null=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('length', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('depth', models.FloatField(default=0.0)),
                ('date', models.ManyToManyField(to='appfactory.dateitem')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfactory.detailvolumeitem')),
                ('product_volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfactory.productvolumeitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_count', models.IntegerField(default=0)),
                ('code', models.CharField(default='', max_length=255, null=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('po', models.CharField(default='', max_length=255, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('volume', models.JSONField(default=dict)),
                ('summary_qty_by_qty', models.JSONField(default=dict)),
                ('summary_qty_by_vol', models.JSONField(default=dict)),
                ('process', models.CharField(default='', max_length=50)),
                ('date', models.ManyToManyField(to='appfactory.dateitem')),
                ('details', models.ManyToManyField(to='appfactory.detailitem')),
            ],
        ),
        migrations.CreateModel(
            name='ShipDetailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50, null=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('color', models.CharField(default='', max_length=50, null=True)),
                ('qty', models.CharField(default='', max_length=50, null=True)),
                ('client', models.CharField(default='', max_length=50, null=True)),
                ('input', models.IntegerField(default=0)),
                ('output', models.IntegerField(default=0)),
                ('note', models.CharField(default='', max_length=255, null=True)),
                ('instock', models.IntegerField(default=0)),
                ('instockVolume', models.FloatField(default=0.0)),
                ('documentDate', models.CharField(default='', max_length=20, null=True)),
                ('qtyByProcess', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfactory.qtyprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ContInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(default='', max_length=50, null=True)),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('contIndex', models.CharField(default='', max_length=10, null=True)),
                ('letter', models.CharField(default='', max_length=5, null=True)),
                ('dest', models.CharField(default='', max_length=50, null=True)),
                ('contType', models.CharField(default='', max_length=10, null=True)),
                ('poNumber', models.CharField(default='', max_length=20, null=True)),
                ('instock', models.IntegerField(default=0)),
                ('instockVolume', models.FloatField(default=0.0)),
                ('qty', models.IntegerField(default=0)),
                ('cyCut', models.ManyToManyField(related_name='cycut_contifor', to='appfactory.dateitem')),
                ('etd', models.ManyToManyField(related_name='etd_contifor', to='appfactory.dateitem')),
                ('psi', models.ManyToManyField(related_name='psi_contifor', to='appfactory.dateitem')),
                ('shipRun', models.ManyToManyField(related_name='shiprun_contifor', to='appfactory.dateitem')),
                ('siCut', models.ManyToManyField(related_name='sicut_contifor', to='appfactory.dateitem')),
                ('details', models.ManyToManyField(related_name='details_ContInfor', to='appfactory.shipdetailitem')),
            ],
        ),
        migrations.CreateModel(
            name='ShipQtyByContainerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('contifor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfactory.continfor')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfactory.shipdetailitem')),
            ],
        ),
    ]
