# Generated by Django 5.1.2 on 2025-01-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continfor',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
