# Generated by Django 5.1.2 on 2024-12-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continfor',
            name='type',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
