# Generated by Django 5.1.2 on 2024-12-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0002_continfor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continfor',
            old_name='type',
            new_name='contIndex',
        ),
        migrations.RenameField(
            model_name='datecanedit',
            old_name='etdVietNam',
            new_name='etd',
        ),
        migrations.AddField(
            model_name='continfor',
            name='contType',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='continfor',
            name='poNumber',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
