# Generated by Django 5.1.2 on 2024-12-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0003_rename_type_continfor_contindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='continfor',
            name='clientname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
