# Generated by Django 5.1.2 on 2024-12-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0004_continfor_clientname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continfor',
            name='date',
        ),
        migrations.AddField(
            model_name='continfor',
            name='cyCut',
            field=models.ManyToManyField(related_name='cycut_contifor', to='appfactory.dateitem'),
        ),
        migrations.AddField(
            model_name='continfor',
            name='etd',
            field=models.ManyToManyField(related_name='etdVietNam_contifor', to='appfactory.dateitem'),
        ),
        migrations.AddField(
            model_name='continfor',
            name='psi',
            field=models.ManyToManyField(related_name='psi_contifor', to='appfactory.dateitem'),
        ),
        migrations.AddField(
            model_name='continfor',
            name='shipRun',
            field=models.ManyToManyField(related_name='shiprun_contifor', to='appfactory.dateitem'),
        ),
        migrations.AddField(
            model_name='continfor',
            name='siCut',
            field=models.ManyToManyField(related_name='sicut_contifor', to='appfactory.dateitem'),
        ),
    ]
