# Generated by Django 5.1.2 on 2024-12-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0005_remove_continfor_date_continfor_cycut_continfor_etd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continfor',
            name='etd',
            field=models.ManyToManyField(related_name='etd_contifor', to='appfactory.dateitem'),
        ),
    ]
