# Generated by Django 5.1.2 on 2024-12-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0006_alter_continfor_etd'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdetailitem',
            name='input',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipdetailitem',
            name='note',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipdetailitem',
            name='ouput',
            field=models.IntegerField(default=0),
        ),
    ]
