# Generated by Django 5.1.2 on 2024-12-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0007_shipdetailitem_input_shipdetailitem_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipdetailitem',
            old_name='ouput',
            new_name='output',
        ),
    ]
