# Generated by Django 5.1.2 on 2024-12-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0008_rename_ouput_shipdetailitem_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdetailitem',
            name='documentDate',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
