# Generated by Django 5.1.2 on 2024-12-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0009_shipdetailitem_documentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdetailitem',
            name='instock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipdetailitem',
            name='instockVolume',
            field=models.FloatField(default=0.0),
        ),
    ]
