# Generated by Django 5.1.2 on 2024-12-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0010_shipdetailitem_instock_shipdetailitem_instockvolume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipdetailitem',
            name='contifor',
        ),
        migrations.AddField(
            model_name='continfor',
            name='details',
            field=models.ManyToManyField(related_name='details_ContInfor', to='appfactory.shipdetailitem'),
        ),
    ]
