# Generated by Django 5.1.2 on 2024-12-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0011_remove_shipdetailitem_contifor_continfor_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='continfor',
            name='instock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='continfor',
            name='instockVolume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='continfor',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
