# Generated by Django 5.1.2 on 2024-12-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0012_continfor_instock_continfor_instockvolume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='continfor',
            name='displaycolor',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
