# Generated by Django 5.1.2 on 2024-12-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0013_continfor_displaycolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continfor',
            name='displaycolor',
        ),
    ]
