# Generated by Django 5.1.2 on 2025-01-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0014_remove_continfor_displaycolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='po',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
