# Generated by Django 5.1.2 on 2025-01-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0015_productitem_name_productitem_po_productitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='process',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productitem',
            name='summary_qty_by_qty',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='productitem',
            name='summary_qty_by_vol',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='productitem',
            name='volume',
            field=models.JSONField(default=dict),
        ),
    ]
