# Generated by Django 5.1.2 on 2025-01-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0016_productitem_process_productitem_summary_qty_by_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateitem',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detailvolumeitem',
            name='this_item_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productvolumeitem',
            name='all_product_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productvolumeitem',
            name='product_volume',
            field=models.FloatField(default=0.0),
        ),
    ]
