# Generated by Django 5.1.2 on 2025-01-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfactory', '0017_alter_dateitem_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty', models.JSONField(default=dict)),
                ('total_vol', models.JSONField(default=dict)),
                ('datelist', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='ShipInfor',
        ),
    ]
